[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "8e0122277d8b01fc1dcbf6c68f775d78434678a2"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "faaaf81085dfe15cec41b96c8e8cbf2add21a96b7a4fe545e2c1e3114c8e7a50"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "6940c25477633e5ef5a1619b0fb4f17211cc9898"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "abc5628f1e170fc736e9db9d3c6f17b44753f53dc518e13d1e34cfaa377ba550"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "fec4661d5b56bbbe14bb9f1e3e1adec0887e9572"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "09bad3fdb70dd73914129b64b81c8e4c772b749d0e27534fcf871b26f7e0c3d8"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "ebfe94460484bc9e8fec646d9008a9e2c27c4608"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "a1caf22d31f08b0083353783fecc4c51c5c11482ed4fb85dcd524c9c448bd7ec"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "fdec838cbd1f57a48fa54e08de64355ffdac3d6b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "2dc760a5a38d7cc0631c4aef262c5527cb4d42345522c288c0ed7a5bc46bea01"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d3ac6554c534438f3b3dbbcb11ded964ee45bcc6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "54dfd0d193a6f99522f9466e6c2ae9beb132848b67837950555cdf1e51d52f8e"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "897ff20c6b457513a76fbdbbe9617c303f9471e8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "9e61bcd2e492391435f262e4dd74c3bc128dc45535afdd2e6fc4eaac65a1260d"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "04d31a72a857bd74e51af5929f379d6c0aed06d7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "06517041165e17f455623c72e79c307f8db7fcc2f4b5e41b3c3b222844b24fe5"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "880e0029a4519fcb0292892a5517d94013d70225"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "929253325be745427e457bdfcf08b1d379e99d9acfb985642e2f245c1cf2b818"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a1ef14ba3591ae34c9110ba326348fc8d5ddde51"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "95e6672e47925514662559cec45573602169854f87fb74cba0ac8ae65bbca9a9"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1881d010c3f3e308cd7d309da79c21ace01bbebf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "ad1ff17a734ac6971762b6b766467042d94172876807f04103916ab2f93b1cb8"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5a36a1bf07530d82f7c1e70e0299ec995bda4184"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "10dd12effdd84c6a2e8b209898e9c4b02cfb1fedc179cf0ff300d1ee50d41730"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "33020139ec08932c3e5169754a3230bcbd185e14"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "c37d3d4bfe91446abceea07235f17008ab98dc201cc5460efaa33d51615eb71e"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "20df47a5b6fad8ee4c94b68a3ab0701b5d91b8c4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "68636971cba8dd7cc4af3253c8a9ae260eb2be81be42fb32201773b7bc606414"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "4ffb94e35547bd275029423b063ab3bc221b5b4e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "d1b57a3e2af71f9781562d69b193c4087889142d871ccf157d1dc54d5680db2b"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "7d08fc841b06fa8747847d5a7afd9918faf9a451"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "859fdbffa3fae92ba6aa26a1cfa1566f80abb08bdf8d48a3e2ec9b08fe61a2a4"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "ae00537c8d51dc899d4b1361c4dbbe2b728b39c5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "d99bc28ff39c5e19e775335f32689fdae8e8df454533e62e62cc3db39c7b39d6"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "916c0c52632f48d777e0f67f9e2e64904b8b6497"
libgfortran_version = "4.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "b3ad5b7eb056d738e351cba13d398e79657fb0526faa8940add7731a5fcda55d"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "974583ce11158105951fdaecd661095336325a46"
libgfortran_version = "5.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "ba6641c0d09bf4f369d61020a2bf3eed46f2b7683ed5fa1ccc220d2ee86d0f71"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "powerpc64le"
git-tree-sha1 = "5234bc446c52828526ef8ff0c2d0b0e41d2984f5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "5a1e726c2718e86e28602ad13e111c245d4ef637dbaffbe064ce8848813768c3"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "powerpc64le"
git-tree-sha1 = "9627493f2f0b484ede81820acfdf670472d932de"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "b2a6b4cc6298c672362a5ad01da30e3898afc5a486cf36aeff800f9977e8dfb0"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "14480a18818b6446e8a2603850166630c3a43c8f"
libgfortran_version = "4.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "c52ab617a74af1e290e1075b444f44194d6feb817a37a65ce662258e01785caa"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "2e4cc77bc297f4bb20779bdc36ebbcd7d289bad1"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "b7eff61882e4a2ce7d2ba5393b010f1015df465759193a1b3053d7a6884c03a4"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "cbc64ee1152382f0a9b89470efb795cc4ae04028"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "af04e3e1892319d3b82f5d54bd294917f980f375b39e2f398673e73212bbfa43"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "f2f652868e1e76ab4d47140770fe4f9241242b5c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "a34b892fd0098158640334e4b627efae3c3424a10be89308e6fc51e1cc1382da"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "94be00b39c4e16883b6ffcfba9745a6797492e87"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "dc6cccab261710d255aa238645020b77be5fd655ec186fa436eaee1ea47ed169"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "449b22658c880f21b9a2179c176b8f0d355d6c31"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "5081b9e6030f5d653a0cd7eefd336e0fba45b910f7e9d83855d2724f1e61be51"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "6f681adeae55792c567b17b2774ea7bcb9eee7b2"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "4fa03c638c7afb6edbc3762fd74538bc999c9dccf5e5a0db6c5e707ebcd83b4d"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "833a3113ce2c2ab5fa70adb5629c8c593785fce0"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "581cbf802a3785fe9ac3179b9dc44b65be00bff20490db8f31dec0c2ca48944a"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "204964fbba137da64238ded269d46d9f07cdbe36"
libgfortran_version = "4.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "e4ee07be362ed875af23227e2671e227f3a21b212760940d2e55c8e025842e5c"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "7a2067064c8e48b0c10644bf298593d7a98c7c61"
libgfortran_version = "5.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "5a99f9dadd93548a64e6a2ccf289fedddc981ecb6593fb405a065e38ca6874f4"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.0+0/GALAHAD.v5.0.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
