[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "ac2a3029ff44d918699c50ea7c07bf0fa52dd54e"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "14a8b857ef1b2ca3965a5db7aaef8b8fd4c5c4a428c4e1269c0e6070a27a84bc"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "4e60dd94b20a2edafdc641f5e48b4a5586a4fcfc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "f7c8ec752251a284ee7d13f8a50d6dd70abcce99fca8535278e4cd286fa0e6ad"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "649d3400cbdaca179e00252218d75f4febffa26d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "fa5e01d06e8d232c503fa5dc5caeb642f1c4070e366ada7f1a887219551f32f1"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "3de91ca0c15e9e9e72660b18be7519c57c220784"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "ca2e3f9d0355bf1d0ab5c9c8a888bef89f934f37bb6e8ae298737da12cc82fd5"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "b5febaa58b57b7266742a2eb47c310810892dfa4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "57ae17caf5790b3e73d54acd4010cfbcb009bb4264b47529affe0c55837ef71e"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "31f9b45ec6be822a884b9a04be9175b39e92d811"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "1572fc4f9df8bdc0ab1af2457c042f4168a5bf94faf58489ed8fdb807a6c12b4"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "c4368af9a44b33caba59528aa7b88f7685e0abb9"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "8bae14223663a1523e619f31242fa79260fe9209bfa2a16164804637a3e3dc46"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f26598f0b0542e7c6ca638afd8068b4cd4ca0a1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "516aa3e6e6fd71cfe5b7e1abcc17546128f392d00144791fe785873190bbd908"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8b940d5b65ad6742cc5849b753b5f15a8ad98a11"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "0b92b02805b3efb84cd8f13b8ed04e5e9efc2134202d502a68bd6acd27c8f5ae"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf8a9ceb49eec97229635480527561720f5788af"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "75728a0b77a93a351f85dfbe627915339fde360f1f079ef2dd586c87c98a7ec7"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4330676c021e075bd6f6fa730049b641c93a5d6e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "b4263b8777631ea1f4667766adcf6426cb631737302b564ce961981820a13fda"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d65451e24292432e158f5f89cf9f5ef66ec77d0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "84c3d1059a29190defcbf74c3d2a3611352327e5e81de1debd55f50e78f12a3d"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "68867a4fa9399449eb2fa72d803e14f5126ea3e1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "fd6a7782de5c9b9e6889951968dc4c862471bdb99f3fd689f06334c0825e4822"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e0eb19ef3ee30ab5f5498b45c771a55960ed13c4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "cb2eb1bb3609a387f6dc59d54c28d89f380eb0390bdbc173046db9cd979fa800"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d91854e2efcde42b0e10d266bc50ae0477e841bd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "90db518304b6a01800bdc4daaf6389c00ec1fe0fc93491b69f843f2f4b2741da"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "82051523a80b6fb3bff1534f3ca34d1c92121469"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "310169be093e41b4d1ed2bb96e5b310105d9095139ecfc77a1ec5096e014303a"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.i686-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "af358d0bf498e8717140661efd0c09bf27b12dab"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "ea8373637f94393c9ef18d6ef87343e716e9a879709e3d96844a74a4bec8efdd"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.i686-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "2dce717d53dcc20549e1dd9f90a24f4e64f95699"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "92b6736f7fd502ee33c5c93c68e8177cb458093ee55e834912e50cb673ce8276"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.i686-linux-musl-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "b4193bb1594785888de00c2b8d75ec05b6144e55"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "3a1d98f6918b73b509fe618d98d1a711e9e033061a2e6597afcac21bb919d993"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.i686-linux-musl-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "bd50db3f43af72179dd0730c5aad322ac6fb9f45"
libgfortran_version = "4.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "1804514c6061163ffa4e05b030920e279cce0ce12e32cfe967407a6c1d917e92"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "dfe1955cffec5f9b38029058692ff79d172b5af4"
libgfortran_version = "5.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "a667b891817a583bccf0d7f1567964bde492ff6b3d102d248ad5ed21261148db"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "powerpc64le"
git-tree-sha1 = "8962bfecb46a9f3da22928463e16b69475a80713"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "cd38c61a76e925399a17f3588d1304f7c73f4f4dd4c5e05f5b8c347a160ba7b0"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "powerpc64le"
git-tree-sha1 = "6d32c7d7a4cfa53c7f957413569d4e6bdc93d76d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "3a0223f154117ed32bfb5585df2402f1acea6984278ea349d75b69e1530ba790"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "de22f9f4066135edbaf27fa9827f44aedbfec3c8"
libgfortran_version = "4.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "0df4929a733f132b471ec08d948e0a92df281ece6e752b90356e975bd2075852"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "5e8ac256075afe691f4b07b32133b0272a9da6ef"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "cc0eb61b9d0d0de2005a49a2fd249f403a9422150e6409ba57c5cd1cb4ef1f48"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "4c78260724dc60206f9cf77cb9ebee16b7e4818d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "c8dc895258f7a8db28136a4736e59ec8d9157ba42740dcc8c5bfb9f0cb7595b8"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "2816a02242517095d56e1dab82e788273dab3089"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "222c27ea62b458b50a9d3c1f72b20a46377088caa3fd4cb816aafecb16a1c8eb"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "29d0fad8b87f4217f51f2558523d70ed9765ac3a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "60f19c89fce6e40a5e0d91748503d011abe5356e1ba38b95d732084e851ff1ef"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "8f33bf5add318147d1b2d0bcaeb22e52d0473f1f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "3a5b754406758c015dcc546ec73857cef9973fd0512405ab2203e877f586f532"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "12f0cc2b6451636f0926c692b276ce9e7b0b0d20"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "1bb816e712c112445bb331c168f5db13ec749395b301a3b696627ad3dd751a5e"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "62c56b4ed050dee377dca5aee1cd0c68eafc4ece"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "e93334ee654582aaf058663c266dda85b2193086cc48a5ecb885a9ac516cae78"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "4d759ebdedcb28355341d6a76033e3e26c937517"
libgfortran_version = "4.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "2cc4759fc77342c94dd2e7819d396ce537dce981652d5b269ff91eb3d30e4ec8"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "67d8366786f16f934f49cb026e373a246a990e6e"
libgfortran_version = "5.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "57643cb13362378a7b1d937b65d136d1a02ee1b8712db2d5686fe1c4ab369576"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.0.1+0/GALAHAD.v5.0.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
