[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "515b4a87eba2d90303e855d734e07ca6edf523e4"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "326579c394c0920c06dc559137282eb4d87cfb783f739e1d25cbbe271ebc4256"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.5.1+0/GALAHAD.v5.5.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "54bd348c281b4f574f5ac8c9d6a7b672c23fe2fb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "18800243675a5cde1dadad57c92e2775c992ccf27f96b2d2c52ecc07b4d0fe0b"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.5.1+0/GALAHAD.v5.5.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "750a2a0bdc22103807fb85fef56664fe102f7d3d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "6397df25bbdaba57c0571240a2cd5ed46ef22469ebe564842d6ad1cf5ab7fabd"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.5.1+0/GALAHAD.v5.5.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "powerpc64le"
git-tree-sha1 = "ddc4f8129485a3783074a613149ac7c084d33b7e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "48823c9f22dbc0713fee2ee978033122bf7d64eb8372fb353e30243bf9ab4d88"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.5.1+0/GALAHAD.v5.5.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "riscv64"
git-tree-sha1 = "980ec29bcda53c91b6217d62760b7b1d8d6b74af"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "a4ef78271ee7cebdb16db600f3bd14536141c244544f40661b10ab034c08dc3f"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.5.1+0/GALAHAD.v5.5.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "0dd656da39391ca24cadbd300579500fddbd7c6d"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "35842316a7d4df406ccac58ff4957cf10d4649a8d946d11a774770f870bd8943"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.5.1+0/GALAHAD.v5.5.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "b77c067f7dc0a8aee247e9b0cb6a4b57464ef933"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "3ffc84057d8b22ce57dd89aaee5596484165dbaba067593e8edc5b67df0ff65b"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.5.1+0/GALAHAD.v5.5.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "f7484f2d2450cc45153fa225a9c06cac11f85284"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "3cee78fa9652887fb09d7a42f7a7047913d42ad0df8bb1ad9cc226cf995d5f6f"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.5.1+0/GALAHAD.v5.5.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "a11544145aa7015c94b6253a52c960a2ca756099"
libgfortran_version = "5.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "a0e72e791d20e1fe17c1d69de086aecc4f9d715a9664124bd265e03fa5ee795f"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.5.1+0/GALAHAD.v5.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
