[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "50aa6ae97dc7e545a450f42ed12ac88d6d2889e4"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "98f3b521f11225337d2b4840d99daa90dd58692c3de950e7ad354d1d06884e3b"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.4.0+0/GALAHAD.v5.4.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "2b1931f872c6d1f9fe295b5dabd482c96c13665a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "cd420ee28813ad1c73a6d2fb1216b6611862b0a4b0e445b1dd223c09f2c702a3"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.4.0+0/GALAHAD.v5.4.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "29866d6e78848d8b374269bae7564c6cb83b90be"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "06d2ec1a8a3a89849b6b1fbec71a8198a8a2ba817dc9db4ab0c64f96cc27927b"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.4.0+0/GALAHAD.v5.4.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "powerpc64le"
git-tree-sha1 = "26d2d52978325aadca6ef453fd0e1398ad01344a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "1e8b3d6a800d9145256f76a459da91d9d2ef628003286b4eea1179273bddb5fb"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.4.0+0/GALAHAD.v5.4.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "riscv64"
git-tree-sha1 = "04cf69e2efd81b7bd86a5cfb30abb12e040cb063"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "cf79c8146e582ccec2828f9f15eb12f61aa3b37f9f0c974c0b983f8b06fa6969"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.4.0+0/GALAHAD.v5.4.0.riscv64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "c6137c0613b48ba12e8c6191a96b4bc279331041"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "18cce74b42bb08e6a0c10657b78d9094a007ce42c27d663c92b270ba87471c59"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.4.0+0/GALAHAD.v5.4.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "e588e9c08f0c84d0e1ece6dce8dcc74bf1017211"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "e7482667c08dbb73369e1a0b6d1c5166f1cfe8dd5f993be409befa226008c9dc"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.4.0+0/GALAHAD.v5.4.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "3eed56efdc0c7aedd1e24b72f301f0e61bc8ccc9"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "732e7c68d2aae85f0c2171acd0c4955903fd0171e5c474b490e65d22125b2ab1"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.4.0+0/GALAHAD.v5.4.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "00b78ce3ab5a3b8e11b194208b7008b0f86abb78"
libgfortran_version = "5.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "1a692254f5b5337875133984317dd7577660784abee0c3ad6f09291dc6060fe4"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.4.0+0/GALAHAD.v5.4.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
