[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "b9563f1dfc47623a16b18e82a181b6b43d375054"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "2060ab2b93383a5b115b1d4b752ce3da540a26ab871cd9d371636fc0a7143e80"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "39f2d45e076d220b42bbc3a30a65822a8c533250"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "1b6c78acc39d7639d5a755c24980bd0c443f359a4c78cd8d6ad159c74def39ef"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "015372aa44d302acd34b0aea46bcae7c01d766d5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "2f6b251a089342f0a2355cc2e888677ea440587d12459fc834fd25ef287cca4e"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "6addc8daadb2eb619f8e226c41d24302bb2ea433"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "58257227b075d8afcbe21c6ddecdb1023a69aa87832293737c7da20a63c8e3a3"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "eb4e7d0957c3b097829317db9aa06949869cd29d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "64fa6f316415a6bd1fa953aae2d8756c154557ceccda4ecae1c293469e2cfd2b"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "bb40b8a223a9618a44d55f92676b1edd6c288278"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "d25e6e82c366116b47260c04b584329331a39e26f08a824a1fd9bd5563b49dc2"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "6495bd51f1a71e36645423cafa5b69438af80b38"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "7131d6b921a3390f5952c20edc9043441f12b6b153d7db23605c212f1c726c4c"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "06872d8aeb98537cf78018bd078a7311daf104ea"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "97e50182bde08404215e880a1f35d72aca5e7e24cb8e9364f2f6f25fef0e87ce"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e0ae088f62865ceed37fd43f8514be58cdd0855b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "9f8da7833d122479d8f16b0af4bf8d00489821ae76241e49fcb00736a2549ce9"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e0c9626d4d378afef5e526d35adcbc6def745cd3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "bc9ee5541379a8de02ac7ff6a9ff209ec99391902f5714a0895169db156c09db"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eeee3e0bd7ec4e9d5f6eab2e8be76f4ad548a97e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "7b196e3eed59afd5d19c61ab4a6dcc093d054155900fd6c3ac63db9577cd51e8"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2ff96d257a3fcde06f558458bc1f037cb3c2390"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "d64c9421b826b73a8e4d3637106396cf40c0ab90ceff25f7fbfc7a80e1158d3b"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "966f696d4bb5537ac7708415fd6e3749aeb5d438"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "fce9895b72de6b274c125a837983a85e037ad01d945a6ae4664dddea6cb0a54f"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8de23c247234eb9a8762a8a8caa59ba381b4ffdd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "d011e28b65e4ce2ee5c287eb193b6604192d49d4991c3a173069fdad66028e06"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db999ba87d8589f302f6c76aec79275aa062d069"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "cae7e51f6ae3af3437fbed2f05d56c16cd99e54ada7b29494452c0f72a3564bc"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "5be9d2911fc3ada7b7d3e7f7b5cf10dd446602bb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "e8fb4148d66b839bc5f977cb672f2a6e511f52430d56987240355a3429a8cc5b"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.i686-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "d136b2be24e808c138b6ff78f84ddcf3ff2e0ef9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "97a37107926127ad1670c9efe2478bdea9ffc49572ae33a176b2be44a983f119"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.i686-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "afc8c91cdfe61e023040e5dd339c46c17685c2d3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "f4aac3ac7697d3b1d0ee0037a381412d1a51bc1d84845b2be05d36377f0d65fc"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.i686-linux-musl-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "0c0fccd332903874573c16c6b8eae8cbf6041472"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "938b67b78c63703ce11ed013124d88c246c30e8feb76f13ea0fb21a6f5ddbf1f"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.i686-linux-musl-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "c066213ad9cb353366a12b99033acc7acd773470"
libgfortran_version = "4.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "97c4cdd0fbbb033f481e9b26cba4fb7b0904a1137ba868181c81d0118748b7e1"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "i686"
git-tree-sha1 = "24e58d1ee4f09142ef6b979099fca7bdfc72b233"
libgfortran_version = "5.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "45ac62e2d64e233f6bd47b4cfde8a28b826406de3c8e50f890b617b2cd458f9c"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "powerpc64le"
git-tree-sha1 = "37c63163c7125f8520ff71175bc4aa05b1d80198"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "e737a364f5851e02d263f792d049f7d750bbede291525fbbf37fd37411b89c34"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "powerpc64le"
git-tree-sha1 = "8f4de7797fd7e6eb0cace72cdf28ca33ddf43250"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "68079919363737bc7a7383b043d64dacd5ad9e479aa14829a486ce9ec007ae6b"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "riscv64"
git-tree-sha1 = "ff6a95baf635fec14241e694cfce6a98fc3f73c9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "797608608221a763c4976be66c50e456d636d4a9d80d6b75b41c1685a1a33011"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "8573070f439f02852f1701bf2241434b4e4a8bad"
libgfortran_version = "4.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "f81cd5ea42c813a040e410f9f6ca668cc239e00d7b9c83cb3e1451c24cc4613a"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "e3832859ebf9478cecad374fbfda5a51dab33740"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "90bfc2f8e10fdf9cdb7201cbf59747e9e4962f00151ea6c308e6080cc2f2d358"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "aaaa77c65792e247d3b7057ff5e4ba8a87876fa2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "0ec4e639928ee069c2925c7ec30f61d2a6975157a767412729bcf56eda2b8c15"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "c9c1329f64609175eaa078b3d6f7792e597c85a5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "ea5649dfcf30f30a9045c2e68d9f9f99cf5218e64d6c1952d8d8a610dfd171f1"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "92043984021fcfd436c7ac9a20237c88458491f6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "ef0b13f85ae1388fa5006fcb9781d49d146160ee31902234732a83b5e7e74160"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "b2393458f883b80ab86968683d56f2c257fda829"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "cb2450f32f7407d09f68efb383cf6cf3ad2488a771260b2e3c840e8e474d06f2"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "f1b5808ddd67b9cc57a1863f52f55cbffc1ce1f8"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "153d094d9a8fa39ff146bab7373cf33ee13673e036437323f0c882f9a12bed0f"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "aaef7f6044596177e62466aaf53c378b1acd8bb2"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "fa30be615cea18636ff8a17596a07daa6b89663a26b3f9be1b5ab43f4743c916"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "4bdd28507e0cded6fd9fdaad1472d9df0023d710"
libgfortran_version = "4.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "c56e3fc27b0e84f39ab7f551b3d56e5da7354a689e4014056ae71230cab127df"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "7453e3adc29c3cca506f876b04e597e55b0bee9a"
libgfortran_version = "5.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "f78040bc1de2df86945e98d73c997428a444592f7006a32d3ae36267c9e51b59"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.1.1+0/GALAHAD.v5.1.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
