[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "9117494506461321db987c4c85482fc6259f860c"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "b367317295007b9d797317f84403863f0ff96d6ed17deb487d0c58bbec0ce199"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.1+0/GALAHAD.v5.2.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "bb84bd7fa1ecc838008569c0326421ae013ddde3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "806d90882eba87b2897476dae5ec4dd0841c0005f85b153f94250d0cfb350f71"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.1+0/GALAHAD.v5.2.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "bf42849391a405ad7439c165cff9744885cb75ef"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "c7064761640b179bbea1976c92aa188ea77b444efdc894f1149c64358fcc7735"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.1+0/GALAHAD.v5.2.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "powerpc64le"
git-tree-sha1 = "82a948726f2b1a8ba047101c0a8942b2e1fa993c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "09032788ca736382ec7a2fd00c4241a9e7f1ec6dcb9eeacd13cdcba5eb98a950"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.1+0/GALAHAD.v5.2.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "riscv64"
git-tree-sha1 = "e4ffd86221ae276440e31e1916c8111b1fe90c0e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "420e6ccd859f01f4147dbac67d66946fd331d2aef0cbe1f26f6b42f527a2d56b"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.1+0/GALAHAD.v5.2.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "40dbfb6937f8582cd5fc69036acd438639884c58"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "a89f14dcd8977ea1858354b294bdf8f74c91cae94d772c4654101ad85a7c1542"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.1+0/GALAHAD.v5.2.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "fe96f381b06943bb00cb83f555891681fbbb868c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[GALAHAD.download]]
    sha256 = "24b760a7179a892dc28bf37583ff644aa4f7d60c590ce4e3af5736b31ecfbe73"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.1+0/GALAHAD.v5.2.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "e910d6dd298173fa5455e878347447326781e91a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[GALAHAD.download]]
    sha256 = "0fe7440d9397900880d26ab0b69c000dd62424eefee37b81a9263e22b539db8f"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.1+0/GALAHAD.v5.2.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[GALAHAD]]
arch = "x86_64"
git-tree-sha1 = "45b3904871e8b3e5305edbec3cf6bb47454bd239"
libgfortran_version = "5.0.0"
os = "windows"

    [[GALAHAD.download]]
    sha256 = "13f3ed67c884e442fd2bde9dcf10bf9f721c83c2ce978d4a24ac4f72ba665178"
    url = "https://github.com/JuliaBinaryWrappers/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.1+0/GALAHAD.v5.2.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
